[project]
name = "agentic-rag"
version = "0.1.0"
description = "A system for agentic Retrieval-Augmented Generation (RAG) using PDF document processing."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pdfplumber>=0.11.7",
]
